'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Strings_en
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SteamCMD_GUI.Resources.Strings.en", GetType(Strings_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto-Scroll.
        '''</summary>
        Friend ReadOnly Property CheckBox_AutoScroll() As String
            Get
                Return ResourceManager.GetString("CheckBox_AutoScroll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect.
        '''</summary>
        Friend ReadOnly Property Button_RconConnect() As String
            Get
                Return ResourceManager.GetString("Button_RconConnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disconnect.
        '''</summary>
        Friend ReadOnly Property Button_RconDisconnect() As String
            Get
                Return ResourceManager.GetString("Button_RconDisconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send.
        '''</summary>
        Friend ReadOnly Property Button_RconSend() As String
            Get
                Return ResourceManager.GetString("Button_RconSend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find.
        '''</summary>
        Friend ReadOnly Property Button_Search() As String
            Get
                Return ResourceManager.GetString("Button_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection.
        '''</summary>
        Friend ReadOnly Property GroupBox_RconConnection() As String
            Get
                Return ResourceManager.GetString("GroupBox_RconConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Console.
        '''</summary>
        Friend ReadOnly Property GroupBox_RconConsole() As String
            Get
                Return ResourceManager.GetString("GroupBox_RconConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Host.
        '''</summary>
        Friend ReadOnly Property Label_RconHost() As String
            Get
                Return ResourceManager.GetString("Label_RconHost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend ReadOnly Property Label_RconPassword() As String
            Get
                Return ResourceManager.GetString("Label_RconPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port.
        '''</summary>
        Friend ReadOnly Property Label_RconPort() As String
            Get
                Return ResourceManager.GetString("Label_RconPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend ReadOnly Property Label_Search() As String
            Get
                Return ResourceManager.GetString("Label_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SteamCMD GUI.
        '''</summary>
        Friend ReadOnly Property MainMenu_Title() As String
            Get
                Return ResourceManager.GetString("MainMenu_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log Viewer.
        '''</summary>
        Friend ReadOnly Property Tab_LogViewer() As String
            Get
                Return ResourceManager.GetString("Tab_LogViewer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RCON Client.
        '''</summary>
        Friend ReadOnly Property Tab_RCON() As String
            Get
                Return ResourceManager.GetString("Tab_RCON", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
